# Sal Docker tasks - main.yml
---
- name: ufw - allow http/https connections
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - http
    - https

- name: generate Diffie-Hellman group
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem "{{ diffie_hellman_size }}"
  args:
    creates: /etc/ssl/certs/dhparam.pem

- name: create sal directories
  file:
    path: "{{ sal_directory }}/{{ item }}"
    mode: 0700
    state: directory
  with_items:
    -
    - compose
    - db

- name: apply docker compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ sal_directory }}/compose/docker-compose.yml"
    owner: root
    group: root
    mode: 0600

- name: run docker compose
  docker_service:
    project_src: "{{ sal_directory }}/compose/"
    remove_volumes: no
    state: "{{ sal_docker_compose_state }}"
    stopped: "{{ sal_docker_compose_stopped }}"
