# Sal (Docker) tasks - main.yml
---
- name: create nginx proxy container
  docker_container:
    name: nginx-proxy
    image: jwilder/nginx-proxy:{{ nginx_proxy_version }}
    state: started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

- name: create sal database directory
file:
  path: /srv/sal/db
  mode: 0777
  state: directory
  
- name: create sal database container
docker_container:
  name: postgres-sal
  image: grahamgilbert/postgres:{{ sal_db_version }}
  state: started
  env:
    DB_NAME: sal
    DB_USER: admin
    DB_PASS: password
  volumes:
    - /usr/local/sal_data/db:/var/lib/postgresql/data

- name: create sal container
docker_container:
  name: sal
  image: macadmins/sal:{{ sal_version }}
  state: started
  env:
    ADMIN_PASS: pass
    DB_NAME: sal
    DB_USER: admin
    DB_PASS: password
    VIRTUAL_PORT: 8000
    VIRTUAL_HOST: a.docker.jacobfgrant.com
  links:
    - postgres-sal:db